---
http_interactions:
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/build
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - application/tar
      Transfer-Encoding:
      - chunked
      X-Registry-Config:
      - eyJjb25maWdzIjp7Imh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxIjp7InVzZXJuYW1lIjoidGR1ZmZpZWxkIiwicGFzc3dvcmQiOiJpOUJmPkpndmZialkvc0pXTWNVOSIsImVtYWlsIjoiZ2l0aHViQHRvbWR1ZmZpZWxkLmNvbSJ9fX0=
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 26 Nov 2014 18:54:18 GMT
    body:
      encoding: UTF-8
      string: "{\"stream\":\"Step 0 : FROM debian:wheezy\\n\"}\r\n{\"stream\":\" ---\\u003e
        f6fab3b798be\\n\"}\r\n{\"stream\":\"Step 1 : ADD / /\\n\"}\r\n{\"stream\":\"
        ---\\u003e b7d888b186ec\\n\"}\r\n{\"stream\":\"Removing intermediate container
        25221dfec744\\n\"}\r\n{\"stream\":\"Successfully built b7d888b186ec\\n\"}\r\n"
    http_version: 
  recorded_at: Wed, 26 Nov 2014 18:54:18 GMT
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/containers/create
    body:
      encoding: UTF-8
      string: '{"Image":"b7d888b186ec","Cmd":["cat","/Dockerfile"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 26 Nov 2014 18:54:18 GMT
      Content-Length:
      - '90'
    body:
      encoding: UTF-8
      string: |
        {"Id":"fc1f3088b00ac32a51b0ec3e2b4c1a9b10d4dd99f872a071c266df5ebd03e64d","Warnings":null}
    http_version: 
  recorded_at: Wed, 26 Nov 2014 18:54:18 GMT
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/containers/fc1f3088b00ac32a51b0ec3e2b4c1a9b10d4dd99f872a071c266df5ebd03e64d/wait
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 26 Nov 2014 18:54:18 GMT
      Content-Length:
      - '17'
    body:
      encoding: UTF-8
      string: |
        {"StatusCode":0}
    http_version: 
  recorded_at: Wed, 26 Nov 2014 18:54:18 GMT
- request:
    method: delete
    uri: https://192.168.59.103:2376/v1.15/containers/fc1f3088b00ac32a51b0ec3e2b4c1a9b10d4dd99f872a071c266df5ebd03e64d
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 204
      message: 
    headers:
      Date:
      - Wed, 26 Nov 2014 18:54:18 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 26 Nov 2014 18:54:18 GMT
- request:
    method: delete
    uri: https://192.168.59.103:2376/v1.15/images/b7d888b186ec?noprune=true
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Wed, 26 Nov 2014 18:54:18 GMT
      Content-Length:
      - '81'
    body:
      encoding: UTF-8
      string: |-
        [{"Deleted":"b7d888b186ecc07a072d976dde7badbf2a025cfdad139af33939d19a824fa887"}
        ]
    http_version: 
  recorded_at: Wed, 26 Nov 2014 18:54:18 GMT
recorded_with: VCR 2.9.3
