---
http_interactions:
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.15/build"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - application/tar
      Transfer-Encoding:
      - chunked
      X-Registry-Config:
      - eyJjb25maWdzIjp7Imh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxIjp7InVzZXJuYW1lIjoidGR1ZmZpZWxkIiwicGFzc3dvcmQiOiJpOUJmPkpndmZialkvc0pXTWNVOSIsImVtYWlsIjoiZ2l0aHViQHRvbWR1ZmZpZWxkLmNvbSJ9fX0=
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Mon, 01 Dec 2014 16:37:56 GMT
    body:
      encoding: UTF-8
      string: "{\"stream\":\"Step 0 : FROM debian:wheezy\\n\"}\r\n{\"stream\":\" ---\\u003e
        f6fab3b798be\\n\"}\r\n{\"stream\":\"Step 1 : ADD / /\\n\"}\r\n{\"stream\":\"
        ---\\u003e 806b147974f8\\n\"}\r\n{\"stream\":\"Removing intermediate container
        508af078aaae\\n\"}\r\n{\"stream\":\"Successfully built 806b147974f8\\n\"}\r\n"
    http_version: 
  recorded_at: Mon, 01 Dec 2014 16:37:57 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.15/containers/create"
    body:
      encoding: UTF-8
      string: '{"Image":"806b147974f8","Cmd":["cat","/Dockerfile"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Mon, 01 Dec 2014 16:37:57 GMT
      Content-Length:
      - '90'
    body:
      encoding: UTF-8
      string: |
        {"Id":"be6da3b1c17fa23a575194df872281d14d188e8129ac3525bbd82cd9d3d24723","Warnings":null}
    http_version: 
  recorded_at: Mon, 01 Dec 2014 16:37:57 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.15/containers/be6da3b1c17fa23a575194df872281d14d188e8129ac3525bbd82cd9d3d24723/wait"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Mon, 01 Dec 2014 16:37:57 GMT
      Content-Length:
      - '17'
    body:
      encoding: UTF-8
      string: |
        {"StatusCode":0}
    http_version: 
  recorded_at: Mon, 01 Dec 2014 16:37:57 GMT
- request:
    method: delete
    uri: "<DOCKER_HOST>/v1.15/containers/be6da3b1c17fa23a575194df872281d14d188e8129ac3525bbd82cd9d3d24723"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 204
      message: 
    headers:
      Date:
      - Mon, 01 Dec 2014 16:37:57 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 01 Dec 2014 16:37:57 GMT
- request:
    method: delete
    uri: "<DOCKER_HOST>/v1.15/images/806b147974f8?noprune=true"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Mon, 01 Dec 2014 16:37:57 GMT
      Content-Length:
      - '81'
    body:
      encoding: UTF-8
      string: |-
        [{"Deleted":"806b147974f8efb31f7ea0452bae828fbbe8fc6517658fb47036f757b6472d07"}
        ]
    http_version: 
  recorded_at: Mon, 01 Dec 2014 16:37:57 GMT
recorded_with: VCR 2.9.3
