---
http_interactions:
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/build"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - application/tar
      Transfer-Encoding:
      - chunked
      X-Registry-Config:
      - eyJjb25maWdzIjp7Imh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxIjp7InVzZXJuYW1lIjoidGx1bnRlciIsInBhc3N3b3JkIjoiams3Z3RpcSIsImVtYWlsIjoidGx1bnRlckBnbWFpbC5jb20ifX19
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Sun, 22 Nov 2015 04:14:48 GMT
    body:
      encoding: UTF-8
      string: "{\"stream\":\"Step 1 : FROM debian:wheezy\\n\"}\r\n{\"stream\":\" ---\\u003e
        b4c4e8b590a7\\n\"}\r\n{\"stream\":\"Step 2 : ADD . /\\n\"}\r\n{\"stream\":\"
        ---\\u003e 3d0bef69d536\\n\"}\r\n{\"stream\":\"Removing intermediate container
        b94ae14711ef\\n\"}\r\n{\"stream\":\"Successfully built 3d0bef69d536\\n\"}\r\n"
    http_version: 
  recorded_at: Sun, 22 Nov 2015 04:14:48 GMT
- request:
    method: delete
    uri: "<DOCKER_HOST>/v1.16/images/3d0bef69d536?noprune=true"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Sun, 22 Nov 2015 04:14:48 GMT
      Content-Length:
      - '81'
    body:
      encoding: UTF-8
      string: |
        [{"Deleted":"3d0bef69d536a3a536c8f2b1bf2fce7a05131d6111fd005fa36c98e58c58fc6b"}]
    http_version: 
  recorded_at: Sun, 22 Nov 2015 04:14:48 GMT
recorded_with: VCR 2.9.2
