---
http_interactions:
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/build
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - application/tar
      Transfer-Encoding:
      - chunked
      X-Registry-Config:
      - eyJjb25maWdzIjp7Imh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxIjp7InVzZXJuYW1lIjoidGR1ZmZpZWxkIiwicGFzc3dvcmQiOiJpOUJmPkpndmZialkvc0pXTWNVOSIsImVtYWlsIjoiZ2l0aHViQHRvbWR1ZmZpZWxkLmNvbSJ9fX0=
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 25 Nov 2014 02:52:15 GMT
    body:
      encoding: UTF-8
      string: "{\"stream\":\"Step 0 : FROM debian:wheezy\\n\"}\r\n{\"stream\":\" ---\\u003e
        f6fab3b798be\\n\"}\r\n{\"stream\":\"Step 1 : ADD / /\\n\"}\r\n{\"stream\":\"
        ---\\u003e 4253f2d36510\\n\"}\r\n{\"stream\":\"Removing intermediate container
        591f295a3236\\n\"}\r\n{\"stream\":\"Successfully built 4253f2d36510\\n\"}\r\n"
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:14 GMT
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/containers/create
    body:
      encoding: UTF-8
      string: '{"Image":"4253f2d36510","Cmd":["cat","/Dockerfile"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 25 Nov 2014 02:52:15 GMT
      Content-Length:
      - '90'
    body:
      encoding: UTF-8
      string: |
        {"Id":"c91c82892997fa588b0d4f5331948273f68dd4f4e1132ed19c20fa51232b9c61","Warnings":null}
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:14 GMT
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/containers/c91c82892997fa588b0d4f5331948273f68dd4f4e1132ed19c20fa51232b9c61/wait
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 25 Nov 2014 02:52:15 GMT
      Content-Length:
      - '17'
    body:
      encoding: UTF-8
      string: |
        {"StatusCode":0}
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:14 GMT
- request:
    method: delete
    uri: https://192.168.59.103:2376/v1.15/containers/c91c82892997fa588b0d4f5331948273f68dd4f4e1132ed19c20fa51232b9c61
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 204
      message: 
    headers:
      Date:
      - Tue, 25 Nov 2014 02:52:15 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:15 GMT
- request:
    method: delete
    uri: https://192.168.59.103:2376/v1.15/images/4253f2d36510?noprune=true
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 25 Nov 2014 02:52:15 GMT
      Content-Length:
      - '81'
    body:
      encoding: UTF-8
      string: |-
        [{"Deleted":"4253f2d3651073fdaa67e5aa1c74a693770df85e909ac0176f7356d8ed03e4a6"}
        ]
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:15 GMT
recorded_with: VCR 2.9.3
