---
http_interactions:
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/images/create?fromImage=debian%3Awheezy
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 25 Nov 2014 02:52:03 GMT
    body:
      encoding: UTF-8
      string: "{\"status\":\"The image you are pulling has been verified\",\"id\":\"debian:wheezy\"}\r\n{\"status\":\"Already
        exists\",\"progressDetail\":{},\"id\":\"511136ea3c5a\"}{\"status\":\"Already
        exists\",\"progressDetail\":{},\"id\":\"f10807909bc5\"}{\"status\":\"Already
        exists\",\"progressDetail\":{},\"id\":\"f6fab3b798be\"}{\"status\":\"Status:
        Image is up to date for debian:wheezy\"}\r\n"
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:02 GMT
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/containers/create
    body:
      encoding: UTF-8
      string: '{"Image":"f6fab3b798be","Cmd":["pwd"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 25 Nov 2014 02:52:03 GMT
      Content-Length:
      - '90'
    body:
      encoding: UTF-8
      string: |
        {"Id":"1c88e6a1132fbeb1aa1605399e20074ff82ad452c5d7fe914ffcf19cbd0736d4","Warnings":null}
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:02 GMT
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/containers/1c88e6a1132fbeb1aa1605399e20074ff82ad452c5d7fe914ffcf19cbd0736d4/start
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: 
    headers:
      Date:
      - Tue, 25 Nov 2014 02:52:03 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:02 GMT
- request:
    method: get
    uri: https://192.168.59.103:2376/v1.15/containers/1c88e6a1132fbeb1aa1605399e20074ff82ad452c5d7fe914ffcf19cbd0736d4/logs?stdout=true
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Date:
      - Tue, 25 Nov 2014 02:52:03 GMT
      Content-Type:
      - application/octet-stream
    body:
      encoding: UTF-8
      string: !binary |-
        AQAAAAAAAAIvCg==
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:02 GMT
- request:
    method: post
    uri: https://192.168.59.103:2376/v1.15/containers/1c88e6a1132fbeb1aa1605399e20074ff82ad452c5d7fe914ffcf19cbd0736d4/wait
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 25 Nov 2014 02:52:03 GMT
      Content-Length:
      - '17'
    body:
      encoding: UTF-8
      string: |
        {"StatusCode":0}
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:03 GMT
- request:
    method: delete
    uri: https://192.168.59.103:2376/v1.15/containers/1c88e6a1132fbeb1aa1605399e20074ff82ad452c5d7fe914ffcf19cbd0736d4
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 204
      message: 
    headers:
      Date:
      - Tue, 25 Nov 2014 02:52:03 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 25 Nov 2014 02:52:03 GMT
recorded_with: VCR 2.9.3
