---
http_interactions:
- request:
    method: get
    uri: https://192.168.59.103:2376/v1.15/version
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.15.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Job-Name:
      - version
      Date:
      - Wed, 26 Nov 2014 18:54:18 GMT
      Content-Length:
      - '148'
    body:
      encoding: UTF-8
      string: |
        {"ApiVersion":"1.15","Arch":"amd64","GitCommit":"39fa2fa","GoVersion":"go1.3.3","KernelVersion":"3.16.7-tinycore64","Os":"linux","Version":"1.3.2"}
    http_version: 
  recorded_at: Wed, 26 Nov 2014 18:54:18 GMT
recorded_with: VCR 2.9.3
