---
http_interactions:
- request:
    method: get
    uri: "<DOCKER_HOST>/v1.16/info"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Sun, 22 Nov 2015 04:15:29 GMT
      Content-Length:
      - '1239'
    body:
      encoding: UTF-8
      string: |
        {"ID":"NJIH:V5P7:62WA:JXSU:QJV7:Q64K:TU6P:J7B3:KQSA:FI4I:WQTH:IWFW","Containers":1,"Images":21,"Driver":"aufs","DriverStatus":[["Root Dir","/mnt/sda1/var/lib/docker/aufs"],["Backing Filesystem","extfs"],["Dirs","23"],["Dirperm1 Supported","true"]],"MemoryLimit":true,"SwapLimit":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":true,"NFd":19,"OomKillDisable":true,"NGoroutines":144,"SystemTime":"2015-11-22T04:15:29.949922995Z","ExecutionDriver":"native-0.2","LoggingDriver":"json-file","NEventsListener":0,"KernelVersion":"4.1.12-boot2docker","OperatingSystem":"Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":null,"Secure":true,"Official":true}},"Mirrors":null},"InitSha1":"","InitPath":"/usr/local/bin/docker","NCPU":1,"MemTotal":1044578304,"DockerRootDir":"/mnt/sda1/var/lib/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"dev","Labels":["provider=virtualbox"],"ExperimentalBuild":false,"ServerVersion":"1.9.0","ClusterStore":"","ClusterAdvertise":""}
    http_version: 
  recorded_at: Sun, 22 Nov 2015 04:15:29 GMT
recorded_with: VCR 2.9.2
